
export  const config = [
    {
        type:"block",
        child:[
            {
                name:"user",
                icon:require("../../../../image/seticon/user.png")
            }
        ]
        
    },
    {
        type:"block",
        child:[
            {
                name:"Wi-Fi",
                icon:require("../../../../image/seticon/WI-Fi.png")
            },
            {
                name:"蓝牙",
                icon:require("../../../../image/seticon/蓝牙.png")
            },
            {
                name:"网络",
                icon:require("../../../../image/seticon/网络.png")
            },
        ],
        
    },
    {
        type:"block",
        child:[
            {
                name:"通知",
                icon:require("../../../../image/seticon/通知.png")
            },
            {
                name:"声音",
                icon:require("../../../../image/seticon/声音.png")
            },
            {
                name:"专注模式",
                icon:require("../../../../image/seticon/专注模式.png")
            },
            {
                name:"屏幕使用时间",
                icon:require("../../../../image/seticon/屏幕使用时间.png")
            },
        ],
        
    },
    {
        type:"block",
        child:[
            {
                name:"通用",
                icon:require("../../../../image/seticon/通用.png")
            },
            {
                name:"外观",
                icon:require("../../../../image/seticon/外观.png")
            },
            {
                name:"辅助功能",
                icon:require("../../../../image/seticon/辅助功能.png")
            },
            {
                name:"控制中心",
                icon:require("../../../../image/seticon/控制中心.png")
            },
        ],
        
    },
    {
        type:"block",
        child:[
            {
                name:"桌面与程序坞",
                icon:require("../../../../image/seticon/桌面与程序坞.png")
            },
            {
                name:"显示器",
                icon:require("../../../../image/seticon/显示器.png")
            },
            {
                name:"墙纸",
                icon:require("../../../../image/seticon/墙纸.png")
            },
            {
                name:"屏幕保护程序",
                icon:require("../../../../image/seticon/屏幕保护程序.png")
            },
            {
                name:"电池",
                icon:require("../../../../image/seticon/电池.png")
            },
        ],
        
    }
]