const 默认状态栏 = [
    {
        name:'访达',
        main:[
            {name:"关于访达",click:()=>console.log('访达')},
            {name:"偏好设置",click:()=>console.log('偏好设置')},
            {name:"隐藏访达",click:()=>console.log('隐藏访达')},
            {name:"服务",click:()=>console.log('服务')},
            {name:"清倒废纸篓",click:()=>console.log('清倒废纸篓')}
        ]
    },
    {
        name:'文件',
        main:[
            {name:"新建访达窗口",click:()=>console.log('新建访达窗口')},
            {name:"新建文件夹",click:()=>console.log('新建文件夹')},
            {name:"打开",click:()=>console.log('打开')},
            {name:"关闭窗口",click:()=>console.log('关闭窗口')},
            {name:"显示简介",click:()=>console.log('显示简介')},
            {name:"重新命名",click:()=>console.log('重新命名')},
            {name:"压缩",click:()=>console.log('压缩')},
            {name:"复制",click:()=>console.log('复制')},
            {name:"制作替身",click:()=>console.log('制作替身')},
            {name:"快速查看",click:()=>console.log('快速查看')}
        ]
    },
    {
        name:'编辑',
        main:[
            {name:"撤销",click:()=>console.log('访达')},
            {name:"重做",click:()=>console.log('偏好设置')},
            {name:"剪切",click:()=>console.log('文件操作')},
            {name:"复制",click:()=>console.log('新建窗口')},
            {name:"粘贴",click:()=>console.log('拷贝')},
            {name:"显示剪切板",click:()=>console.log('文件操作')},
            {name:"开始听写",click:()=>console.log('新建窗口')},
            {name:"表情与符号",click:()=>console.log('拷贝')}
        ]
    },
    {
        name:'显示',
        main:[
            {name:"为图标",click:()=>console.log('访达')},
            {name:"为分栏",click:()=>console.log('偏好设置')},
            {name:"为列表",click:()=>console.log('文件操作')},
            {name:"为画廊",click:()=>console.log('新建窗口')},
            {name:"整理",click:()=>console.log('拷贝')},
            {name:"显示所有标签页",click:()=>console.log('访达')},
            {name:"显示标签页栏",click:()=>console.log('偏好设置')},
            {name:"显示路径栏",click:()=>console.log('文件操作')},
            {name:"显示状态栏",click:()=>console.log('新建窗口')},
        ]
    },
    {
        name:'窗口',
        main:[
            {name:"关于访达",click:()=>console.log('访达')},
            {name:"偏好设置",click:()=>console.log('偏好设置')},
            {name:"文件操作",click:()=>console.log('文件操作')},
            {name:"新建窗口",click:()=>console.log('新建窗口')},
            {name:"拷贝",click:()=>console.log('拷贝')}
        ]
    },
    {
        name:'帮助',
        main:[
            {name:"macOS帮助",click:()=>console.log('macos帮助')},
            {name:"查看macOS的新功能",click:()=>console.log('查看新功能')},
            {name:"MAC新手? 了解基础知识",click:()=>console.log('了解基础知识')},
        ]
    },
]

export default 默认状态栏